/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FZUIAnchor from "./framework/FZUIAnchor"
import FZMapUI from "./game/view/FZMapUI"
import FZGaiBianCarNode from "./game/view/FZGaiBianCarNode"
import FZDestoryCarNode from "./game/view/FZDestoryCarNode"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="view/FZGetCarDialog.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("framework/FZUIAnchor.ts",FZUIAnchor);
        reg("game/view/FZMapUI.ts",FZMapUI);
        reg("game/view/FZGaiBianCarNode.ts",FZGaiBianCarNode);
        reg("game/view/FZDestoryCarNode.ts",FZDestoryCarNode);
    }
}
GameConfig.init();