/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import QUIAnchor from "./framework/QUIAnchor"
import QMapView from "./game/view/QMapView"
import QChangeCarNode from "./game/view/QChangeCarNode"
import QCleanNode from "./game/view/QCleanNode"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="view/LoadingView.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("framework/QUIAnchor.ts",QUIAnchor);
        reg("game/view/QMapView.ts",QMapView);
        reg("game/view/QChangeCarNode.ts",QChangeCarNode);
        reg("game/view/QCleanNode.ts",QCleanNode);
    }
}
GameConfig.init();